# Generated by Django 5.0.6 on 2024-09-04 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residences', '0001_initial'),
        ('usuarios', '0002_customuser_residencia_pontodeusodeagua_sensordefluxo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userr', to='usuarios.customuser'),
        ),
        migrations.AddField(
            model_name='pontodeusodeagua',
            name='residencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_uso_agua', to='residences.residencia'),
        ),
    ]
