# Generated by Django 5.0.6 on 2024-09-04 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDeFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=50)),
                ('ponto_uso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores_fluxo', to='residences.pontodeusodeagua')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDeConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_consumo', to='sensors.sensordefluxo')),
            ],
        ),
    ]
