# Generated by Django 5.0.6 on 2024-09-04 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0002_initial'),
        ('usuarios', '0002_customuser_residencia_pontodeusodeagua_sensordefluxo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertaconsumo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_consumo', to='usuarios.customuser'),
        ),
    ]
