# Generated by Django 5.1.1 on 2024-11-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='titulo',
            field=models.TextField(default='Alerta'),
        ),
    ]
